In [17]:
#Co-relation Coefficient:
import numpy as np

In [18]:
data = np.random.randint(1,10,(5,5))

In [19]:
data

array([[4, 9, 3, 4, 4],
       [3, 5, 1, 6, 9],
       [1, 4, 9, 1, 8],
       [2, 3, 7, 8, 6],
       [6, 7, 5, 3, 3]])

In [20]:
np.corrcoef(data)

array([[ 1.        ,  0.16571045, -0.20491148, -0.51781562,  0.63219542],
       [ 0.16571045,  1.        , -0.00871843,  0.16558159, -0.56212246],
       [-0.20491148, -0.00871843,  1.        ,  0.34224679, -0.16261091],
       [-0.51781562,  0.16558159,  0.34224679,  1.        , -0.79907829],
       [ 0.63219542, -0.56212246, -0.16261091, -0.79907829,  1.        ]])

In [21]:
np.round(np.corrcoef(data),2)

array([[ 1.  ,  0.17, -0.2 , -0.52,  0.63],
       [ 0.17,  1.  , -0.01,  0.17, -0.56],
       [-0.2 , -0.01,  1.  ,  0.34, -0.16],
       [-0.52,  0.17,  0.34,  1.  , -0.8 ],
       [ 0.63, -0.56, -0.16, -0.8 ,  1.  ]])

In [22]:
sales_data=np.random.randint(150,500,(10,5))

In [23]:
sales_data=np.random.randint(150,500,(10,5))

In [31]:
sales_data

array([[386, 492, 285, 460, 153],
       [468, 368, 430, 340, 393],
       [264, 178, 222, 262, 444],
       [461, 445, 470, 203, 401],
       [181, 284, 402, 208, 233],
       [480, 263, 283, 355, 410],
       [383, 192, 363, 276, 305],
       [287, 498, 343, 430, 495],
       [473, 476, 193, 406, 469],
       [303, 442, 177, 321, 202]])

In [33]:
sales_data.sum()

17258

In [35]:
sales_data[6:8, :].sum()

3572

In [ ]:
#defining a function

In [16]:
def greet():
    print("Hello Harshita")

In [18]:
greet()

Hello Harshita


In [20]:
#Return Statement
def multiply(a,b,c):
    return a*b*c
result = multiply(3,4,5)
print(result)

60


In [37]:
def greet (arg):
    print(f"Good Morning, {arg}!")
greet("Coders")

Good Morning, Coders!


In [39]:
greet("Students")

Good Morning, Students!


In [22]:
#Arbitary Arguments
def add(*args):
    return sum(args)
print(add(1,2,3))  #output:6
print(add(4,5,6,7))  #output:22

6
22


In [41]:
def print_details(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}:{value}")
print_details(name="Alice",age=30,city="New york")

name:Alice
age:30
city:New york


In [ ]:
#Lambda Functions

In [28]:
add = lambda a, b: a*b
print(add(8,5))

40


In [30]:
def add(a,b):
    return a+b
print(add(8,5))

add= lambda a,b:a+b

13


In [33]:
multiply = lambda a,b: a*b
print(multiply(8,5))

40


In [45]:
Cube = lambda x:x *x*x
print(Cube(5))

125


In [47]:
z= lambda x,y: x- y
print(z(5,6))

-1


In [49]:
import array as arr

eg_array = arr.array('i',[1,2,3,4,5])
print(eg_array[0])
print(eg_array[2])
print(eg_array[3])

eg_array[1]=10
print(eg_array)

eg_array.append(6)
print(eg_array)

eg_array.extend([7,8,9])
print(eg_array)

eg_array.remove(10)
print(eg_array)

eg_array.pop(6)
print(eg_array)





1
3
4
array('i', [1, 10, 3, 4, 5])
array('i', [1, 10, 3, 4, 5, 6])
array('i', [1, 10, 3, 4, 5, 6, 7, 8, 9])
array('i', [1, 3, 4, 5, 6, 7, 8, 9])
array('i', [1, 3, 4, 5, 6, 7, 9])
