In [ ]:
#find the number elements in array

In [1]:
import numpy as np


In [3]:
a = np.array([[1,2,3],[4,5,6],[5,8,12]])
print(a.size) #it gives the size
print(a.shape)
print(a.ndim)
print(a.dtype)

9
(3, 3)
2
int32


In [21]:
x=np.random.randint(0,20,(6,5))
print(x)

[[15  0 18 15 14]
 [ 3 12 16  2 16]
 [17 19 14 19 13]
 [ 9 18  4  8 16]
 [19  5  6 11 11]
 [ 4  7 15 10  7]]


In [ ]:
#x.shape()

In [13]:
x.ravel()

array([19, 12,  2, 12, 17, 19, 13, 14, 10, 17, 12,  0,  8, 12,  0, 17,  4,
       14, 11, 12,  0,  1, 13, 12, 18,  2,  5,  9, 15,  7])

In [29]:
x.reshape(3,10)

array([[15,  0, 18, 15, 14,  3, 12, 16,  2, 16],
       [17, 19, 14, 19, 13,  9, 18,  4,  8, 16],
       [19,  5,  6, 11, 11,  4,  7, 15, 10,  7]])

In [31]:
print(x)

[[15  0 18 15 14]
 [ 3 12 16  2 16]
 [17 19 14 19 13]
 [ 9 18  4  8 16]
 [19  5  6 11 11]
 [ 4  7 15 10  7]]


In [17]:
y=x.ravel()

In [19]:
y.reshape(10,3)
print(x)

[[19 12  2 12 17]
 [19 13 14 10 17]
 [12  0  8 12  0]
 [17  4 14 11 12]
 [ 0  1 13 12 18]
 [ 2  5  9 15  7]]


In [37]:
x1 = np.array([[2,3],[4,3]])
print(x1)

[[2 3]
 [4 3]]


In [41]:
x2 = np.array([[4,5],[6,7]])
print(x2)

[[4 5]
 [6 7]]


In [43]:
np.vstack([x1,x2])

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [45]:
np.hstack([x1,x2])

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [47]:
np.concatenate([x1,x2],axis=0)

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [49]:
np.concatenate([x1,x2],axis=1)

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [ ]:
#Numpy array Mathematics-sum

In [53]:
d = np.arange(24,dtype='float') #0,1,.......,23
print(d)
print(d.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]
float64


In [55]:
import numpy as np
np.sum([10,30,60,54,68,258])

480

In [57]:
a = [10,20]
b = [20,5]
np.sum([a,b]) #10+20 = 30 + 20+5 = 25 ,30+25=55

55

In [63]:
import numpy as np
#creating two 2D arrays
array1 = np.array([[1,2,3],
                  [4,5,6]])
array2 = np.array([[7,8,9],              #[8,10,12],[14,16,18]
                  [11,12,13]])
array3 = np.array([[8,6,9],
                  [10,9,13]])
#Adding the two arrays
sum_array = array1 + array2 +array3
print("Addition:\n", sum_array)
sum_array.ndim

Addition:
 [[16 16 21]
 [25 26 32]]


2

In [ ]:
#substraction

In [65]:
import numpy as np
np.subtract(10,20)

-10

In [69]:
#subtraction of two arrays:

a=np.array([0,1,6])
b=np.array([0,5,3])
c=np.array([0,1,2])
#np.subtract([0,1,2])

sub = a-b-c
print(sub)

[ 0 -5  1]


In [71]:
#using different shapes(Broadcasting)
import numpy as np

a= np.array([[1,2],[6,8],[6,5]])
b = np.array([5,4])

#Addition from each row of a using broadcasting
result = a+b
print("Result of a + b with broadcasting:\n", result)

Result of a + b with broadcasting:
 [[ 6  6]
 [11 12]
 [11  9]]
