In [ ]:
#Multiplication of numpy array

In [92]:
array1 = np.array([[1,2,3],
                   [4,5,3],
                   [4,6,1]])
array2 = np.array([[7,8,4],
                   [4,1,2],
                   [2,3,2]])

product_array = array1 * array2
print("Multiplication:\n",product_array)

Multiplication:
 [[ 7 16 12]
 [16  5  6]
 [ 8 18  2]]


In [94]:
import numpy as np

In [96]:
array1 = np.array([[1,2,3],
                   [4,6,1]])
array2 = np.array([2,3,2])

product_array = array1 * array2
print("Multiplication:\n",product_array)

Multiplication:
 [[ 2  6  6]
 [ 8 18  2]]


In [26]:
#matrix multiplication

In [27]:
m*n, n*k #number of rows and numbers of columns should be same 

In [28]:
x1 = np.random.randint(0,10,(2,2))
x2 = np.random.randint(0,10,(2,2))

In [29]:
x1

array([[3, 8],
       [4, 8]])

In [30]:
x2

array([[2, 9],
       [3, 3]])

In [31]:
np.dot(x1,x2)

array([[30, 51],
       [32, 60]])

In [ ]:
#string functions

In [41]:
x = np.array([1,2,3,'data'])

In [43]:
x

array(['1', '2', '3', 'data'], dtype='<U11')

In [45]:
np.char.capitalize(x)

array(['1', '2', '3', 'Data'], dtype='<U11')

In [48]:
np.char.center(x,10,fillchar='*') #we can passing any special charcater or alphabets also

array(['****1*****', '****2*****', '****3*****', '***data***'],
      dtype='<U10')

In [50]:
x=np.array([1,2,3,'data engineering'])

In [52]:
x

array(['1', '2', '3', 'data engineering'], dtype='<U16')

In [54]:
print(np.char.upper(x))
print(np.char.lower(x))
print(np.char.title(x))


['1' '2' '3' 'DATA ENGINEERING']
['1' '2' '3' 'data engineering']
['1' '2' '3' 'Data Engineering']


In [56]:
np.char.split(x)

array([list(['1']), list(['2']), list(['3']),
       list(['data', 'engineering'])], dtype=object)

In [60]:
y = np.array(["Data Science","Machine Learning"])

In [68]:
np.char.split(y,sep='e')

array([list(['Data Sci', 'nc', '']), list(['Machin', ' L', 'arning'])],
      dtype=object)

In [64]:
np.char.count(y,"a")

array([2, 2])

In [66]:
np.char.count(y,"a")

array([2, 2])

In [70]:
np.char.startswith(y,"d")

array([False, False])

In [72]:
np.char.replace(y,'a','xxxxxxx')

array(['Dxxxxxxxtxxxxxxx Science', 'Mxxxxxxxchine Lexxxxxxxrning'],
      dtype='<U28')

In [74]:
np.char.rjust(y,20,fillchar="*")

array(['********Data Science', '****Machine Learning'], dtype='<U20')

In [76]:
np.char.ljust(y,20,fillchar="*")

array(['Data Science********', 'Machine Learning****'], dtype='<U20')

In [ ]:
#Time Base functions

In [ ]:
import numpy as np
#Creating two 2D arrays
array1 = np.array

In [100]:
#Division of array
array1 = np.array([[10,20,30],
                   [40,50,60]])
array2 = np.array([[3,4,5],
                 [10,5,3]])

division_array = array1 / array2
print("Division:\n",division_array)
print(division_array.dtype)

Division:
 [[ 3.33333333  5.          6.        ]
 [ 4.         10.         20.        ]]
float64


In [78]:
a = np.array([1,2,3,4,5])
exp_a = np.exp(a)
print("Original array:",a)
print("Exponential of the array:",exp_a)

Original array: [1 2 3 4 5]
Exponential of the array: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [80]:
import math
math.e

2.718281828459045

In [90]:
#expo, sqrt,sin,cos,log
a=np.array([2,4,6])
print("sqrt of a:",np.sqrt(a))
print("sin of a:",np.sin(a))
print("cos of a:",np.cos(a))
print("log of a:",np.log(a))

sqrt of a: [1.41421356 2.         2.44948974]
sin of a: [ 0.90929743 -0.7568025  -0.2794155 ]
cos of a: [-0.41614684 -0.65364362  0.96017029]
log of a: [0.69314718 1.38629436 1.79175947]


In [102]:
#Aggregate functions
a = np.array([1,2,4,5,6,7,8,9])
print("Sum:",np.sum(a))  #42
print("Minimum Value:",np.min(a))  #1
print("Mean Value:",np.mean(a))
print("Median Value:",np.median(a))
print("Corelation Coefficient:",np.corrcoef(a))
print("Standard Deviation:",np.std(a))


Sum: 42
Minimum Value: 1
Mean Value: 5.25
Median Value: 5.5
Corelation Coefficient: 1.0
Standard Deviation: 2.6339134382131846
