In [ ]:
#Butterfly pattern qsn hmwrk

In [ ]:
#pascal's triangle


In [ ]:
#fibonacci series

In [ ]:
#Numpy (numerical python)
#is a powerful library for numerical computations in python.
#it provides support for arrays, matrices,and many mathematical functions to operate on these dsa.

In [1]:
x = [1,2,3]
for i in x:
    print(i/2)

0.5
1.0
1.5


In [13]:
x = [2,4,6,8,10]
for i in x:
    print(i/2)

1.0
2.0
3.0
4.0
5.0


In [15]:
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [17]:
import numpy as np
x=np.array([1,2,3])
print(x)

[1 2 3]


In [19]:
x*2

array([2, 4, 6])

In [ ]:
#Numpy has rich set of numpy functions :
#set1 = Random functions:

In [39]:
data=np.random.randint(0,10,(5,4))
data

array([[2, 9, 3, 7],
       [8, 8, 9, 3],
       [4, 5, 6, 0],
       [8, 0, 6, 8],
       [5, 3, 3, 5]])

In [41]:
data[1: , :2]

array([[8, 8],
       [4, 5],
       [8, 0],
       [5, 3]])

In [43]:
data[2:4,1: ]

array([[5, 6, 0],
       [0, 6, 8]])

In [45]:
data[-2:-4,-1: ]

array([], shape=(0, 1), dtype=int32)

In [25]:
import numpy as np
np.random.randint(0,10,6) #randint is random integers

array([4, 0, 1, 1, 4, 1])

In [29]:
np.random.rand(10)

array([0.02562348, 0.34134861, 0.53083163, 0.01634323, 0.52301909,
       0.95245631, 0.02880961, 0.217544  , 0.95217299, 0.51922541])

In [31]:
np.random.rand(2)

array([0.88769153, 0.03255412])

In [33]:
np.random.randint(100,200,2)

array([186, 166])

In [ ]:
#Numpy slicing


In [47]:
#1D array
a = np.array([2,3,4])
print(a)

[2 3 4]


In [49]:
#2D array
b = np.array([[2,4,6],[8,10,12],[5,6,7]])
print(b)

[[ 2  4  6]
 [ 8 10 12]
 [ 5  6  7]]
