In [1]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((4,4),0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
import numpy as np

In [ ]:
#1D array


In [11]:
#2D
a = np.array([2,4,6],[4,5,6],[6,5,7])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [13]:
x= np.array([[[1,2,3], [4,5,6]], [[4,5,6],[8,8,7]]])
print(x)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [8 8 7]]]


In [15]:
x= np.array([[[1,2,3], [4,5,6]], [[4,5,6],[8,8,7]]])
print(x)

print(type(x))
x.ndim

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [8 8 7]]]
<class 'numpy.ndarray'>


3

In [17]:
#Initialize an array
b=np.ones((3,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [23]:
np.arange(1,20,1) #it will arrange withh interval

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [27]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [29]:
np.linspace(5,10,4) 

array([ 5.        ,  6.66666667,  8.33333333, 10.        ])

In [31]:
np.eye(5) #eye refers to identical matrics

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
import numpy as np

# Create the NumPy array
data = np.array([[5, 4, 0, 1],
                  [11, 4, 10, 7],
                  [7, 10, 5, 6],
                  [7, 12, 10, 4],
                  [3, 7, 3, 4]])

# Print the array
print(data)

[[ 5  4  0  1]
 [11  4 10  7]
 [ 7 10  5  6]
 [ 7 12 10  4]
 [ 3  7  3  4]]


In [37]:
data.sum()

120

In [39]:
dt=[1,3,4]
dt.sum()

AttributeError: 'list' object has no attribute 'sum'

In [41]:
data.max()

12

In [43]:
data.min()

0

In [45]:
data.sum()

120

In [47]:
data.mean()

6.0

In [ ]:
#ndarray.shape:

In [49]:
b=np.array([[4,5,6],[6,8,10]])
print(b.shape)

(2, 3)


In [51]:
a = np.array([[2,4,6,4],[5,6,7,8],[8,10,12,4]])
print("Original Array:\n", a)
a.shape=(6,2)
print("Changed Array:\n",a)

a.shape=(4,3)
print("Changed Array:\n",a)

Original Array:
 [[ 2  4  6  4]
 [ 5  6  7  8]
 [ 8 10 12  4]]
Changed Array:
 [[ 2  4]
 [ 6  4]
 [ 5  6]
 [ 7  8]
 [ 8 10]
 [12  4]]
Changed Array:
 [[ 2  4  6]
 [ 4  5  6]
 [ 7  8  8]
 [10 12  4]]


In [65]:
b=np.array([[1,2,3],[4,5,6],[5,8,8],[5,6,4]])
#b.shape=(6,1)
print(b)
print(b.ndim)


[[1 2 3]
 [4 5 6]
 [5 8 8]
 [5 6 4]]
2


In [61]:
z=np.arange(24)
z.shape=(4,2,3)
print(z)
print(z.ndim)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
3
