Problem Statement:
You work in XYZ Corporation as a Data Analyst. Your corporation has told you to 
use the NumPy package and do some tasks related to that.
Tasks To Be Performed:
1. Create a 3x3 matrix array with values ranging from 2 to 10.
2. Create a NumPy array having user input values and convert the integer
type to the float type of the elements of the array. For instance: Original
array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]
3. Write a NumPy program to append values to the end of an array. For
instance: Original array: [10, 20, 30] . After that, append values to the end
of the array: [10 20 30 40 50 60 70 80 90]
4. Create two NumPy arrays and add the elements of both the arrays and
store the result in sumArray.
5. Create a 3x3 array having values from 10-90 (interval of 10) and store that
in array1
Perform the following tasks:
a. Extract the 1st row from the array
b. Extract the last element from the array

In [7]:
import numpy as np

In [8]:
matrix = np.arange(2, 11).reshape(3, 3)

print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [9]:
user_input = input("Enter numbers: ")
print(user_input)
float_array = np.array(user_input.split(), dtype=float)
print("Float array:", float_array)

1 2 3 4 5 6 7 8
Float array: [1. 2. 3. 4. 5. 6. 7. 8.]


In [10]:
original_array = np.array([10, 20, 30])
print("Original array:", original_array)
values_to_append = [40, 50, 60, 70, 80, 90]
new_array = np.append(original_array, values_to_append)
print("After appending:", new_array)

Original array: [10 20 30]
After appending: [10 20 30 40 50 60 70 80 90]


In [11]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

sumArray = np.add(array1,array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Sum Array:", sumArray)


Array 1: [1 2 3]
Array 2: [4 5 6]
Sum Array: [5 7 9]


In [12]:
array1 = np.arange(10, 100, 10).reshape(3, 3)
print("Original 3x3 Array:\n", array1)

first_row = array1[0]
print("\nFirst row:", first_row)

last_element = array1[-1, -1]
print("Last element:", last_element)


Original 3x3 Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

First row: [10 20 30]
Last element: 90
