In [1]:
import numpy as np
np.random.randint(0,10,4)

array([8, 5, 4, 0])

In [2]:
array=np.random.randint(0,10,(3,5))


In [3]:
array

array([[5, 3, 6, 1, 0],
       [6, 6, 4, 7, 3],
       [3, 1, 5, 1, 4]])

In [4]:
x= np.array([[[1,2,3], [4,5,6]], [[4,5,6],[8,8,7]]])
print(x)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [8 8 7]]]


In [11]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [13]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [17]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [19]:
np.linspace(9,90,10)

array([ 9., 18., 27., 36., 45., 54., 63., 72., 81., 90.])

In [21]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
import numpy as np
# Create the NumPy array
data = np.array([[5, 4, 0, 1],
[11, 4, 10, 7],
[7, 10, 5, 6],
[7, 12, 10, 4],
[3, 7, 3, 4]])
# Print the array
print(data)

[[ 5  4  0  1]
 [11  4 10  7]
 [ 7 10  5  6]
 [ 7 12 10  4]
 [ 3  7  3  4]]


In [31]:
dt=[1,3,4]
sum(dt)

8

In [33]:
a=np.array([[2,4,6,4],[5,6,7,8],[8,10,12,4]])
print("original Array:\n",a)
a,shape=(6,2)
print("changed array:\n",a)

original Array:
 [[ 2  4  6  4]
 [ 5  6  7  8]
 [ 8 10 12  4]]
changed array:
 6
